stages:
  - build

cache:
  paths:
    - _ccache/

variables:
  MESON_TEST_TIMEOUT_MULTIPLIER: 2
  G_MESSAGES_DEBUG: all
  MESON_COMMON_OPTIONS: "--buildtype debug --wrap-mode=nodownload --prefix /usr"

.build:
  before_script:
    - cp -r $HOME/subprojects/* subprojects/

fedora-x86_64:
  extends: .build
  image: registry.gitlab.gnome.org/gnome/unity-software/fedora:v2
  stage: build
  except:
    - tags
  script:
    - meson ${MESON_COMMON_OPTIONS}
            -Drpm_ostree=true
            -Dmalcontent=true
            -Dsysprof=enabled
            _build
    - ninja -C _build
    - .gitlab-ci/run-tests.sh
            --no-suite packagekit
            --no-suite fwupd
            --no-suite libglib-testing
            --no-suite malcontent
  artifacts:
    reports:
      junit: "_build/${CI_JOB_NAME}-report.xml"
    name: "unity-software-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "_build/config.h"
      - "_build/meson-logs"
      - "_build/${CI_JOB_NAME}-report.xml"

debian-stable-x86_64:
  extends: .build
  image: registry.gitlab.gnome.org/gnome/unity-software/debian-stable:v2
  stage: build
  except:
    - tags
  script:
    - meson ${MESON_COMMON_OPTIONS}
            -Drpm_ostree=false
            -Dmalcontent=false
            -Dsysprof=disabled
            _build
    - ninja -C _build
    - .gitlab-ci/run-tests.sh
            --no-suite packagekit
            --no-suite fwupd
            --no-suite fedora-langpacks
  artifacts:
    reports:
      junit: "_build/${CI_JOB_NAME}-report.xml"
    name: "unity-software-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "_build/config.h"
      - "_build/meson-logs"
      - "_build/${CI_JOB_NAME}-report.xml"
